# Generated by Django 5.2.3 on 2025-08-15 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('investment_type', models.CharField(choices=[('stock', 'Stock'), ('mutual_fund', 'Mutual Fund'), ('bond', 'Bond'), ('crypto', 'Cryptocurrency'), ('gold', 'Gold'), ('other', 'Other')], default='other', max_length=20)),
                ('total_amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('expected_return_rate', models.DecimalField(blank=True, decimal_places=2, help_text='As percentage', max_digits=5, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coach.investment')),
            ],
        ),
    ]
