# Generated by Django 5.2.3 on 2025-08-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_investment_investmenttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmenttransaction',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
