# Generated by Django 5.2.3 on 2025-08-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_rename_type_investmenttransaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expected_return_rate',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='maturity_date',
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_amount_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
