# Generated by Django 5.2.3 on 2025-08-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_transaction_user_alter_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.goal'),
        ),
    ]
